services:
  productpage-08:
    image: product-page/08
    container_name: productpage-08
    ports:
      - "9080:9080"
    depends_on:
      - details-08
      - reviews-08
    environment:
      - GROUP_NUM=08
    networks:
      - app_network

  details-08:
    image: details/08
    container_name: details-08
    ports:
      - "9081:9080"
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  reviews-08:
    image: reviews-v1/08
    container_name: reviews-08
    ports:
      - "9082:9080"
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=false
    depends_on:
      - ratings-08
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  ratings-08:
    image: ratings/08
    container_name: ratings-08
    ports:
      - "9083:9080"
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge
