version: "3.3"
services: #Define los servicios que serán ejecutados en contenedores
  g08-details: #Nombre del servicio
    container_name: g08-details #Nombre del contenedor
    image: g08/details #Imagen utilizada para este servicio
    ports:
      - "9083:9080" #Mapea el puerto 9080 del contenedor al puerto 9083 del host
  g08-ratings: #Nombre del servicio
    container_name: g08-ratings #Nombre del contenedor
    image: g08/ratings #Imagen utilizada para este servicio
    ports:
      - "9082:9080" #Mapea el puerto 9080 del contenedor al puerto 9082 del host
  g08-reviews: #Nombre del servicio
    container_name: g08-reviews #Nombre del contenedor
    image: g08/reviews #Imagen utilizada para este servicio
    ports:
      - "9081:9080" #Mapea el puerto 9080 del contenedor al puerto 9081 del host
    environment: #Establece las variables de entorno
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=false
      - STAR_COLOR=black
      - RATINGS_HOSTNAME=g08-ratings
  g08-productpage: #Nombre del servicio
    container_name: g08-productpage #Nombre del contenedor
    image: g08/productpage #Imagen utilizada para este servicio
    ports:
      - "9080:9080" #Mapea el puerto 9080 del contenedor al puerto 9080 del host
    environment: #Establece las variables de entorno
      - DETAILS_HOSTNAME=g08-details
      - REVIEWS_HOSTNAME=g08-reviews
      - RATINGS_HOSTNAME=g08-ratings
